---
title: "11. Writing Automated Tests"
date: 2022-11-25
author: "Jordan Schnur jordan@jordanschnur.com"
id: 20221125151806
keywords:
  - "testing"
  - "automated"
  - "qa"
---

# 11. Writing Automated Tests
Rust type system does what it can to ensure program correctness. However correctness is a complex concept and the type system can not catch everything.

_What are test in rust?_: Test are functions that verify non-test code is functioning in the expected manner. They usually follow three steps:
1. Set up any needed data or state
2. Run code you want to test
3. Assert the results are what you expect

Rust provides some helpers for test. Such as the #test attribute, several macros and the #should_panic attribute.

### How to write a test
By added the #test attribute (#[test]) to a function you tell Rust that this function is now a test. Rust will build a test runner binary that runs all test and reports on which test passed or failed.

Creating a library with cargo will automatically generate a test for us to look at. 
You can run the test with #cargotest (`cargo test`)
```rust
pub fn add(left: usize, right: usize) -> usize {
    left + right
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_works() {
        let result = add(2, 2);
        assert_eq!(result, 4);
    }
}
```

The assert macro comes in several flavours and is how you assert your code is doing what it is supposed to do.

#assert: Panics if value is false `assert!(false)`
#asserteq: Panics if value is not equal to given value. `assert_eq!(1, 2)`
#assertnq: Panics if value is equal to given value `assert_nq!(1, 1)`

`assert_eq` and `assert_nq` use #PartialEq and #Debug traits under the hood. Meaning, if you want to use these assertions on your own struct or enum you can add the`#[derive(PartialEq, Debug)]` annotation.

You can also add custom error messages on a test fail with `assert`.
```rust
#[test]
fn greeting_contains_name() {
	let result = greeting("Carol");
	assert!(
		result.contains("Carol"),
		"Greeting did not contain name, value was `{}`",
		result
	);
// ---- tests::greeting_contains_name stdout ----
// thread 'main' panicked at 'Greeting did not contain name, value was `Hello!`', src/lib.rs:12:9
}

```

We can use the #should_panic attribute to test for `panic` in our code.
```rust
pub struct Guess {
    value: i32,
}

impl Guess {
    pub fn new(value: i32) -> Guess {
        if value < 1 || value > 100 {
            panic!("Guess value must be between 1 and 100, got {}.", value);
        }

        Guess { value }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[should_panic]
    fn greater_than_100() {
        Guess::new(200);
    }
}
```

We can use the #expected parameter on `should_panic` to be more precise.
```rust
impl Guess {
    pub fn new(value: i32) -> Guess {
        if value < 1 {
            panic!(
                "Guess value must be greater than or equal to 1, got {}.",
                value
            );
        } else if value > 100 {
            panic!(
                "Guess value must be less than or equal to 100, got {}.",
                value
            );
        }

        Guess { value }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[should_panic(expected = "less than or equal to 100")]
    fn greater_than_100() {
        Guess::new(200);
    }
}
```

It is possible to use a result for testing as well.
```rust
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() -> Result<(), String> {
        if 2 + 2 == 4 {
            Ok(())
        } else {
            Err(String::from("two plus two does not equal four"))
        }
    }
}
```
> **_NOTE ℹ️:_** You can not use the `#[should_panic]` attribute on a test with `Result<T, E>`. Instead use `assert!(value.is_err())`

